# The basic descriptions of the graph processing platform.
platform.name = ArcadeDB
platform.acronym = arcadedb
platform.version = 1.0
platform.link = https://github.com/ArcadeData/ldbc_graphalytics_platforms_arcadedb

# Home directory of ArcadeDB (optional, for reference only in embedded mode)
platform.arcadedb.home =
